target("parser")
    add_packages("llvm")
    set_kind("static")
    add_deps("LLtool", "basic", "ast", "lexer", "sema")
    add_rules("lltool")
    add_files("Modula-2.g")
    add_files("Parser.cppm", {public = true})
    add_files("M2Parser.cppm", {public = true})
