task:
    name: FreeBSD 13.2
    freebsd_instance:
        image_family: freebsd-13-2
    environment:
        LLVM_ROOT_DIR: /usr/local/llvm16
        CC: $LLVM_ROOT_DIR/bin/clang
        BUILD_DIR: $CIRRUS_WORKING_DIR/../build
        PATH: ${LLVM_ROOT_DIR}/bin:${PATH}
    install_tools_script: |
        cd $CIRRUS_WORKING_DIR/..
        pkg install -y git cmake ninja llvm16
    checkenv_script: |
        sysctl -n hw.ncpu
        cmake --version
        ninja --version
    compile_script: |
        mkdir $BUILD_DIR
        cmake -G Ninja \
              -DLLVM_CMAKE_DIR=${LLVM_ROOT_DIR}/lib/cmake/llvm \
              -DLLVM_EXTERNAL_LIT=${LLVM_ROOT_DIR}/bin/llvm-lit \
              -B $BUILD_DIR -S $CIRRUS_WORKING_DIR
        cmake --build $BUILD_DIR --target LLtool
        cmake --build $BUILD_DIR --target ASTtool
        cmake --build $BUILD_DIR --target m2lang
        $BUILD_DIR/bin/m2lang --version
    test_script: |
        cd $BUILD_DIR
        ninja check-all
